version: "3.9"
services:
  nginx:
    ports:
      - "3000:80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
  my-blog:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/my-blog
      - /my-blog/node_modules
      # - ./config/nodemon.json:/app/nodemon.json
    environment:
      - NODE_ENV=development
      - MONGO_USER=Bader
      - MONGO_PASSWORD=myPassword
      - SESSION_SECRET=someSecret
      - REDIS_USER=Bader
      - REDIS_PASSWORD=myPassword
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=articles
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Bader
      - MONGO_INITDB_ROOT_PASSWORD=myPassword
  # redis:
  #   command:
  #     - redis-server --requirepass myPassword